# Generated by Django 3.1.6 on 2021-02-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='cvr_url',
            new_name='cover_url',
        ),
    ]
